### ISSUE TITLE
Testing FTP Server

### ISSUE THREAD

**Issue by bill-orange** [Monarch73/MicroHomebridgeAlexaEsp8266#1]
First off, nice work.  I tested the FTP server as a standalone in my existing code on an ESP8266.  Scary Fast.  I have found that the usual FTP Server for the ESP8266 crashes when probed by 'Advanced IP Scanner'.  Yours does not.

One problem, however. Of the 20 files in my SPIFFS only 16 list.  One is shown with a truncated file name.  Is there some size limit that I am violating with 20 files?

Any advice?

**Comment by Monarch73** [comment]
Sorry for the late response.

Thank you for testing my code. The FTP-Server is only handling a very limited set  of commands with very limited capabilities. It was created to serve one single specific purpose, so it's far from being a full featured FTP-Server.
